dist: trusty

language: c

os:
  - linux

compiler:
  - gcc

env:
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
  - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
  - TARGET_CPU=x86 BUILD_CONFIGURATION=Release

install:
  - sudo pip install codecov
  - sudo apt-get install -qq cppcheck
  - sudo apt-get install valgrind
  - sudo apt-get install cmake
  - sudo wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz
        
script:
  - cd IZ-1
  - mkdir build
  - cd build
  - cmake CMakeLists.txt
  - cmake  --build .
  - gcov main.c
  - cd Google_tests
  - valgrind --tool=memcheck --leak-check=yes ./Tests
  - cd ..
  - cppcheck --enable=warning,performance,information *.c

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
