dist:     trusty

language: cpp

os:
  - linux

compiler:
  - gcc

env:
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
  - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
  - TARGET_CPU=x86 BUILD_CONFIGURATION=Release

install:
  - sudo apt-get install cppcheck
  - sudo apt-get -qq update
  - sudo apt-get install -y valgrind cmake
  - sudo cmake -DBUILD_SHARED_LIBS=ON .
  - sudo make

script:
  - cd IZ-2
  - cppcheck *.c
  - mkdir build
  - cd build
  - cmake ../
  - make
  - valgrind *.c
