dist: trusty

language: c

os:
  - linux

compiler:
  - gcc

env:
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
  - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
  - TARGET_CPU=x86 BUILD_CONFIGURATION=Release

install:
  - sudo pip install codecov
  - sudo apt-get install -qq cppcheck
  - sudo apt-get install valgrind
  - sudo apt-get install cmake
  - sudo wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz

before_script:
  - cmake -DCMAKE_BUILD_TYPE=Debug -DWRAP_VALGRIND=ON .
        
script:
  - cd IZ-1
  - mkdir build
  - cd build
  - cmake --build
  - cd -
  - cd Google_tests
  - ctest --output-on-failure
  - cd -
  - gcov main.c
  - cppcheck --quiet --error-exitcode=1 .

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
