dits: trusty
sudo: required

language: cpp
after_success:
  -bash <(curl -s https://codecov.io/bash)

os:
  -linux
  -osx

compiler:
  -gcc
  -clang

env:
  -TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
  -TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
  -TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
  -TARGET_CPU=x86 BUILD_CONFIGURATION=Release

matrix:
  exclude:
    -os: osx
     compiler: gcc
     env:
      TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
      TARGET_CPU=x86 BUILD_CONFIGURATION=Release

install:
  -sourse
    CI/Travis/install.sh

script:
  -mkdir build
  -cd build
  -cmake --build
  -ctest --output-on-failure

deploy:
  provider: releases
  file: <package-file>
  skip_cleanup: true
  overwrite: true

api_key:
  secure: <encrypted-github-token>

on:
  tags:true